### ISSUE TITLE
Please add `npmf` to `goreleaser.yml` files for deb and rpm files?

### ISSUE THREAD

**Issue by arran4** [Zebradil/cloudflare-dynamic-dns#73]
I usually add:
```
nfpms:
  -
    vendor: NAME
    homepage: https://WEBSITE/
    maintainer: NAME <EM@IL>
    description: NA
    license: Private
    formats:
      - apk
      - deb
      - rpm
    release: 1
    section: default
    priority: extra
```
